name: Build QMK firmware
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/qmk/qmk_cli
        strategy:
            fail-fast: false
            matrix:
                liatris-keymaps:
                - file: plywood2-tarmak3.json
                  name: plywood3
                moonlander-keymaps:
                - file: plywood2-tarmak3-moonlander.json
                  name: plywood3-moonlander
        steps:
        - name: Disable git safe directory checks
          run : git config --global --add safe.directory '*'

        - name: Checkout QMK
          uses: actions/checkout@v3
          with:
            repository: qmk/qmk_firmware
            submodules: recursive

        - name: Checkout userspace
          uses: actions/checkout@v3
          with:
            path: users/${{ github.actor }}

        - name: Build liatris firmware
          run : qmk compile "users/${{ github.actor }}/${{ matrix.liatris-keymaps.file }}"
          env:
            CONVERT_TO: liatris

        - name: Build moonlander firmware
          run : qmk compile "users/${{ github.actor }}/${{ matrix.moonlander-keymaps.file }}"

        - name: Archive firmware
          uses: actions/upload-artifact@v3
          continue-on-error: true
          with:
            name: ${{ matrix.keymaps.name }}_${{ github.actor }}-${{ github.ref_name }}
            path: |
                readme.md
                license.md
                *.hex
                *.bin
                *.uf2
