name: Build QMK firmware
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/qmk/qmk_cli
        strategy:
            fail-fast: false
            matrix:
                keymaps:
                - file: seniply-tarmak2.json
                  name: seniply
                - file: plywood-tarmak2.json
                  name: plywood
        steps:
        - name: Disable git safe directory checks
          run : git config --global --add safe.directory '*'

        - name: Checkout QMK
          uses: actions/checkout@v3
          with:
            repository: qmk/qmk_firmware
            submodules: recursive

        - name: Checkout userspace
          uses: actions/checkout@v3
          with:
            path: users/${{ github.actor }}

        - name: Build firmware
          run : qmk compile "users/${{ github.actor }}/${{ matrix.keymaps.file }}"
          env:
            CONVERT_TO: liatris


        - name: Archive firmware
          uses: actions/upload-artifact@v3
          continue-on-error: true
          with:
            name: ${{ matrix.keymaps.name }}_${{ github.actor }}-${{ github.ref_name }}
            path: |
                readme.md
                license.md
                *.hex
                *.bin
                *.uf2
